### ISSUE TITLE
Missing dependancy zmq_utils.h

### ISSUE THREAD

**Issue by sunkin351** [zeromq/libzmq#1749]
MSVC build relies on this dependency.

**Comment by sunkin351** [comment]
This is resolved in pull request #1748 .

**Comment by c-rack** [comment]
@sunkin351 `zmq_utils.h` was removed with intent in #1747 :-)

**Comment by hintjens** [comment]
We want to remove this file from the project.

**Comment by hintjens** [comment]
I'm fixing the MSVC files now...

**Comment by sunkin351** [comment]
How do I undo a commit? I need to resolve merge conflicts and I am failing.

**Comment by c-rack** [comment]
No need to undo the commit. Just use a fresh master, `git rm` the file and submit a new pull request.

**Comment by hintjens** [comment]
You can use "git reset d53da43" (whatever the last good commit is)

Then git pull from the upstream repo again.

If that all fails, then delete your repo and re-clone it.

If that still fails, then delete your remote fork and re-fork it, then
re-clone it.

**Comment by sunkin351** [comment]
I am having a hard time pulling from origin... What does github know this repository by?

**Comment by bluca** [comment]
If you run this command it should show the following:

    git remote -v
    origin	git@github.com:sunkin351/libzmq.git (fetch)
    origin	git@github.com:sunkin351/libzmq.git (push)

To add the ZeroMQ remote, use the following:

    git remote add upstream git@github.com:zeromq/libzmq.git

Then first ensure that you have no work on your master branch that you want to save. If you do, create a new branch, as the following commands will drop any commit in master that is not in zeromq's master. Then, to put it back in sync with zeromq's master branch, do:

    git fetch upstream
    git checkout master
    git reset --hard upstream/master
    git checkout <YOUR_WORKING_BRANCH>
    git rebase -i master

In the interactive rebase, you can check which commits to carry on and which to drop.

**Comment by bluca** [comment]
@sunkin351 once the master branch of your fork and of this repository are back in sync (see previous comment), you can keep your version up to date with:

    git checkout master
    git pull --rebase upstream master

**Comment by sunkin351** [comment]
This has been fixed to the point where I can compile.

**Comment by evoskuil** [comment]
I'm still seeing this error in all builds:
https://travis-ci.org/libbitcoin/libbitcoin-server/jobs/106396668#L1260
https://travis-ci.org/libbitcoin/libbitcoin-explorer/jobs/106197363#L1472

**Comment by sunkin351** [comment]
#1759 should fix that... It will delete the *.cpp counterpart of zmq_utils.h.

**Comment by sunkin351** [comment]
If it doesn't, then I will reopen the issue.

**Comment by hintjens** [comment]
@sunkin351 I appreciate the efforts but could you please stop making commits on this for now? It's creating more work for us.

@evoskuil it's a dependency in CZMQ, which I'm fixing now.

**Comment by evoskuil** [comment]
@hintjens Ah, yes - thanks!

**Comment by sunkin351** [comment]
I actually don't know how to recover properly when you don't merge my changes, so, ya, I'm gonna stop, probably indefinitely.

**Comment by bluca** [comment]
@sunkin351 - sorry about your troubles. Git can have a steep learning curve at the beginning, I assure you we've all been there at some point! But there's a light at the end of the (short) tunnel :-)

If you see one of my earlier comments in this discussion, you can find the exact commands to restore your fork to a sane state. I strongly recommend using the git command line tool rather than Github's proprietary GUI thing, as that's very limited.

**Comment by sunkin351** [comment]
Thanks, I think I prefer the command-line tool this time, because its a lot less confusing and feel I have more control over what I am doing. (though I will still use the GUI for committing.)
