### ISSUE TITLE
4.1.2: Assertion failed: Connection reset by peer (zeromq\src\signaler.cpp:298)

### ISSUE THREAD

**Issue by minrk** [zeromq/libzmq#1808]
## Environment
- Windows 10 x64
- zeromq installed via pyzmq bundle (libzmq-4.1.2)
- Compiler: MSVC9 (Windows SDK 7.0 / VS2008)
## Reproduction

...is difficult, but for at least one user, leaving a Jupyter notebook running can die with any of the following asserts:

```
Assertion failed: Connection reset by peer (src\signaler.cpp:181)
Assertion failed: Connection reset by peer (src\signaler.cpp:298)
Assertion failed: nbytes == sizeof (dummy) (src\signaler.cpp:303)
Assertion failed: ok (src\mailbox.cpp:94)
```

The mailbox assert is longstanding and still open at #1108. Any ideas on what might be the cause of the connection resets or the size mismatch?

**Comment by somdoron** [comment]
Which socket type are you using?

**Comment by minrk** [comment]
There will be several SUB and DEALER sockets in the dying process.

**Comment by somdoron** [comment]
Can it be something like firewall? Is it  a virtual machine or PC?

**Comment by minrk** [comment]
It could be a firewall, I don't have access to the failing machine. I believe it is a real machine (cc @jveitchmichaelis for more details).

**Comment by jveitchmichaelis** [comment]
It's a PC - local notebook.

**Comment by somdoron** [comment]
Few questions:
* How long does it take to this to happen?
* Is the application idle (didn't receive message for long time, maybe hours?)
* Is firewall on?
* Does the notebook come out from sleep?

**Comment by jveitchmichaelis** [comment]
Sorry - I meant the Jupyter notebook is running as a local server. It's a desktop PC. The Windows firewall is on.

The time varies - I'll try measuring it properly though. It happens both when idle and in the middle of running code (at least so it seems). My desktop is set not to sleep, so I don't think it's that.

I'll try:

1) Jupyter with no notebook open
2) Idle notebook
3) Notebook in an infinite loop. I don't think the particular piece of code matters, the crashes seem arbitrary.

**Comment by somdoron** [comment]
Can you try with firewall of as well?

**Comment by jveitchmichaelis** [comment]
Yep will do, I'll see if turning on more verbose debugging in Jupyter throws up anything as well.

**Comment by JimChenTaiwan** [comment]
Hi, 
We have the same situation.
Environment:
- Windows 10 x64
- both ZMQ 4.0.4 and 4.1.4 x86
- Compiler: VS2013 x86 build

Reproduction:
- Always crashed at 2 hours after server & client connected.
- error code:
- 　　Assertion failed: Connection reset by peer (..\..\..\src\signaler.cpp:298) or
- 　　Assertion failed: ok (..\..\..\src\mailbox.cpp:82)

We have tested this on three computers, and two of which will have this crash problem.
Can anyone help us?

**Comment by somdoron** [comment]
So recently someone changed the signaler to use random port, this might
make firewall work harder, I'm not sure if it is part of 4.1.4 or 4.0.4,
but what I suggest is compiling with reverting the following commit:

https://github.com/zeromq/libzmq/commit/7e09306cb369f4c345850627f3969be153eaa3cf

Or bottom line, in config.hpp make sure the signaler_port is set to 5905
and not 0.

Also in firewall make sure to allow tcp connection on port 5905 to the
application.

Let me know if this help.

**Comment by JimChenTaiwan** [comment]
OK! Thanks for your suggestion, We will try it.

We also found another problem, 
When we only executed the "zmq:socket->connect" side of zmq program, 
it didn't crash after 2 hours, (because it is not connected?)
but it crashed when we close the "zmq:socket" and "zmq::context".
If we close the program before 2 hours, it will act OK!
It will show the error code:
　　Assertion failed: Connection reset by peer (......\src\signaler.cpp:252)

**Comment by hintjens** [comment]
We need to make this configurable, since reusing the same port leads to
different problems. Hence that patch.

**Comment by JimChenTaiwan** [comment]
[pic1]
![1456385320653](https://cloud.githubusercontent.com/assets/17444597/13312970/9b503a32-dbd5-11e5-8cb5-c32b1b24b8ea.jpg)
[pic2]
![1456385365827](https://cloud.githubusercontent.com/assets/17444597/13312972/9fdfa51a-dbd5-11e5-8cde-f76730286b26.jpg)

Hi,
We used the built-in "local_thr.exe" as test program only.
After 2 hours, we found two TCP port states have been changed from "ESTABLISHED" to "FIN_WAIT1" as you can see in the [pic1].
And after a while, the "local_thr.exe" test program crashed as the [pic2] shows.
Why it always happened after 2 hours?
Thanks a lot.

**Comment by somdoron** [comment]
Did you try same test with firewall disabled?

**Comment by JimChenTaiwan** [comment]
Yes, I have ran some tests with firewall disabled, but it crashed after 2 hours.
I didn't test "local_thr.exe" with firewall disabled yet, I'll try it afterward.

**Comment by somdoron** [comment]
@JimChenTaiwan are you using windows 10 as well?

**Comment by JimChenTaiwan** [comment]
Yes, I test it on Windows 10 x64 ver.

**Comment by mseagrief** [comment]
I'm seeing what I think is identical behaviour here as well.

Running the following:
- Windows 10 x64
- zeromq compiled with Visual Studio 2013 x64 using [`f9c8687`](https://github.com/zeromq/libzmq/commit/f9c86872e5e7bdd1c11e8f16f1be4eef54eb3c58)

After almost exactly two hours the following assert fires:

   `Assertion failed: Connection reset by peer (..\..\..\..\src\signaler.cpp:351)`
 
Similar behaviour occurs if compiled with poll enabled rather than select:

   `Assertion failed: pfd.revents & POLLIN (..\..\..\..\src\signaler.cpp:248)`

Running the same build of our software on Windows 7 doesn't demonstrate this issue.

I'm using inproc connections and running `inproc_thr` (with a Sleep call added at the bottom of the for loop in worker to slow things down to hit 2 hours) reproduces the issue. Invoked as `inproc_thr 64 1000000`. After two hours the assert above fires.

Additionally:
 - Changing signaler_port to 5905 doesn't help.
 - Disabling Windows firewall doesn't appear to help

**Comment by somdoron** [comment]
@mseagrief does it matter if the socket is idle or not?

**Comment by somdoron** [comment]
it seems like issue with windows 10, I tried to google it without much success, can you open an issue with Microsoft?

**Comment by mseagrief** [comment]
@somdoron I'll do some tests today with the socket idle and report back.

As to reporting to Microsoft, I'm not sure what I'd be reporting. I'm not sufficiently familiar with the ZeroMQ internals to make a useful bug report. That said I'll spend some time in the next few days doing so and see if I can isolate the issue

**Comment by mseagrief** [comment]
ZeroMQ 3.2.5 doesn't appear to exhibit this behaviour.

Just running zmq_init and then sleeping for 3 hours doesn't crash. However 5 minutes after starting to use the sockets (using inproc_thr) the assert fires.

Running zmq_init and then creating and binding a PULL socket and then sleeping asserts after 2hrs.

**Comment by mseagrief** [comment]
It looks like the code added to address #1608 causes this behaviour to be triggered under Windows 10. Both the poll and select cases appear to work without triggering the assert with the code block in signaler.cpp commented out.

As for what the underlying issue is I'm unsure. I tried that code as it was the most significant change I could see in signaler.cpp comparing 3.2.5 against the current git master.

**Comment by tnthao** [comment]
having the same issue. easy way to reproduce this problem is have a large number of subscribers active and then simulate a congested/broken network using a tool called clumsy (i used ver 0.2). in the tool enable "drop" and "out of order" and increase the percentages. depending on your network load, it should crash eventually.

**Comment by lytboris** [comment]
#2334 is about connection reset by peer too. Take a look.

**Comment by SylvainCorlay** [comment]
I was also seeing such crashes in 4.1.5 but not anymore in 4.2.1

**Comment by SylvainCorlay** [comment]
I am seeing a lot of these `Assertion failed: nbytes == sizeof (dummy)` in `signaler.cpp:364`.

**Comment by PolarNick239** [comment]
We use jupyter qtconsole as embedded python console in our application, and many our users faced the same bug leading to application crash. It happens even in idle application.

Affected OS:
 - 10.0.14393 (Win10)
 - 6.1.7601 (Win7 SP1/Server 2008 R2 SP1)

Problem encountered with ZeroMQ 4.1.5 (PyZMQ 15.4.0) and ZeroMQ 4.1.6 (PyZMQ 16.0.2).

Error message: ```Connection reset by peer```

Stacktrace:
```
libzmq.cp35-win_amd64.pyd!zmq::zmq_abort(const char * errmsg_) Line 85 C++
libzmq.cp35-win_amd64.pyd!zmq::signaler_t::recv() Line 303 C++
libzmq.cp35-win_amd64.pyd!zmq::mailbox_t::recv(zmq::command_t * cmd_, int timeout_) Line 93 C++
libzmq.cp35-win_amd64.pyd!zmq::socket_base_t::process_commands(int timeout_, bool throttle_) Line 1054 C++
libzmq.cp35-win_amd64.pyd!zmq::socket_base_t::recv(zmq::msg_t * msg_, int flags_) Line 955 + 0xd bytes C++
libzmq.cp35-win_amd64.pyd!zmq_msg_recv(zmq_msg_t * msg_, void * s_, int flags_) Line 601 + 0xe bytes C++
```

Is there any workaround? Maybe some old versions don't have this problem?

**Comment by mseagrief** [comment]
@PolarNick239 for my use case I reverted out the changes in #1608 and compiled up my own binaries. I've been successfully using them for some time now, albeit with fairly light workloads.

It's on my list to re-visit this and bump up the version of ZeroMQ we're using to see if it's resolved, but not high priority at the moment as it is working.

I spent a fair while digging around using various of the low level tracing tools in Windows, but nothing conclusive and they're not tools I've used before so I wasn't 100% certain I was looking in the correct place.

**Comment by PolarNick239** [comment]
@mseagrief Thanks! I will make a test with reverted #1629 and write here my results when I will have a time.

**Comment by caidongyun** [comment]
help ! ports are occupie, who  connect? 12580 occupie
https://github.com/zeromq/libzmq/issues/2598

**Comment by UniversalAE** [comment]
I am having this problem too.   Consistent crashes at around 2 hours.   Running PUB/SUB exclusively.  May be associated with simultaneous use of websockets for WSS connection to remote host in app running ZMQ PUB server.  C# app WEBSOCKET-sharp and ZMQ C# CLR.  Have disabled WEBSOCKET-sharp and this reduces the frequency of events.   ZMQ is unusable unless this problem is resolved.  Need apps to run 24/7 with no unresolvable events.  WEBSOCKET-sharp with no ZMQ operates 24/7 with no events.  I'm currently looking for alternative methods for interprocess communication that will take the place of ZMQ functionality.    This thread is 1.5 years old with no suggested resolution.  That is very unacceptable for a problem so consistently reproduced.

**Comment by UniversalAE** [comment]
As a followup to the issue comment I made 5 days ago.   I have completed my search for an alternate MQ.   I have successfully implemented the same process with RabbitMQ.   I have not had to encapsulate anything with try-catch.   It simply works as expected with no assertion errors.   I now have 4 simultaneous applications running with 1 PUB and 3 SUB end points in each all intercommunicating to each other at 5ms intervals for a period of days and still running, even through random externally induced TCP communication drop out.  **I urge everyone to stop wasting their time with ZeroMQ.**   ZeroMQ is damaged with no prospect for resolution.  ZeroMQ has excellent documentation.   That's as far as it goes.  Regretfully, I'm abandoning ZeroMQ.

**Comment by mseagrief** [comment]
Thanks for the tip re: RabbitMQ. I'll take a look, I've been putting off upgrading our ZMQ binaries for a long while now.

We're still running locally built binaries with #1629 removed without issue. But I wholly agree about assertions like these firing in production code being deeply broken.

**Comment by UniversalAE** [comment]
The move to RabbitMQ I reported 17 days ago has been so successful I feel compelled to report it.   ZERO truely ZERO errors since the last report.  It's been nearly a month of 24/7 messaging between all processes.  Millions of transactions.  Perhaps Billions of flawless object messaging transactions.

**Comment by sigiesec** [comment]
The code locations of the reported assertions are:
https://github.com/zeromq/zeromq4-1/blob/ebc1d60cf12d8ce50fde432093d8d0e7354d4539/src/signaler.cpp#L181

https://github.com/zeromq/zeromq4-1/blob/ebc1d60cf12d8ce50fde432093d8d0e7354d4539/src/signaler.cpp#L298

https://github.com/zeromq/zeromq4-1/blob/ebc1d60cf12d8ce50fde432093d8d0e7354d4539/src/signaler.cpp#L303

https://github.com/zeromq/zeromq4-1/blob/ebc1d60cf12d8ce50fde432093d8d0e7354d4539/src/mailbox.cpp#L94

**Comment by sigiesec** [comment]
The first location, in signaler_t::send was changed twice ca. 6 months ago, by #2360 and #2362. The resulting state is quite contradictory, as #2362 meant to revert #2360, but left unreachable code.

**Comment by bluca** [comment]
Could you please send a fix for it?

**Comment by sigiesec** [comment]
@bluca: I can send a fix to remove the unreachable code, but I think there was a point in the original #2360 PR that is related to the issue reported in the ticket. Probably, the send loop should actually be continued at least for some error codes.

**Comment by sigiesec** [comment]
@UniversalAE It's great to hear that you found a working solution for your use case. Please be aware that ZeroMQ and RabbitMQ are not easily comparable, they have different strengths and weaknesses for a particular problem, and operate on different levels of abstraction. RabbitMQ is a message broker, which ZeroMQ is a message queuing library (which can be used to build a broker). Of course, it would be great to resolve the apparent bug in ZeroMQ reported in this issue as soon as possible.

**Comment by UniversalAE** [comment]
Sigiesec,  I agree with variance of abstraction between the two products.  I actually prefer the ZeroMQ approach.   But, in its current state of operation ZeroMQ is a severely damaged product.  I need it to operate without error for 24/7 ad infinitum.  ZeroMQ operates for 2 hours and then fails with an unresolvable crash to the OS all emanating from signaler.cpp.   For over a year and half others have reported the same problem.   ZeroMQ is simply unusable in this state, I am not prepared nor do I have time to debug other peoples code, and I have moved on.  The fact that this has been a problem for so long, reported by so many, is in itself deplorable.

**Comment by yoshi4cs** [comment]
I had the same issue but resolved it.
I have anaconda 5.0.1 (pyzmq 16.0.2) installed on Windows 10 x64. After running Jupyter notebook, it always crashed in 2 hours with assertion failure errors.

My cause should be related to TDI filter (but I don't fully understand what it is).
In my case, I uninstalled Networx and now it's working perfectly.
[This comment](https://github.com/Microsoft/WSL/issues/1554#issuecomment-339743927) helped me identifying the cause.

Hope this helps other people.

**Comment by anonEmoss** [comment]
Uninstalling Networx has fixed this issue for me too. Thank you!

**Comment by crosscode-nl** [comment]
This happens also in libzmq-4.2.2, Windows build. 

Assertion failed: Connection reset by peer (..\..\..\..\src\signaler.cpp:352)
Assertion failed: Connection reset by peer (..\..\..\..\src\signaler.cpp:352)
Assertion failed: Connection reset by peer (..\..\..\..\src\signaler.cpp:352)

Unfortunately, a library like this that terminates an application because of a connection reset by peer is unusable. 

Is this behavior the same on posix platforms?

**Comment by bluca** [comment]
@crosscode-nl try with latest code from master, there were a few fixes in that area. Also check for that Networkx program others are mentioning, as it seems to be messing with the platform.

**Comment by crosscode-nl** [comment]
The latest master branch does not solve this issue. 

Nu such software like Networkx is installed. 

It is installed in a VMWare environment though. I noticed localhost connections get killed sometimes. (Or even blackholed.) 


To test zeromq after these issues, i now kill all tcp connections with sysinternals tcpview. With the knowledge that (event local) TCP connections can get removed by the OS or other software, I believe it should be able to recover from this, or give an error that can be handled. It should not terminate the application.

I'm also wondering why it uses local TCP connections internally?

**Comment by bluca** [comment]
> To test zeromq after these issues I now kill all tcp connections with sysinternals tcpview. With the knowledge that (even local/loopback) TCP connections can get removed by the OS or other software, I believe it should be able to recover from this, or give an error that can be handled. It should not terminate the application.

Sorry, but if the internal event pipe becomes unreliable, all hell breaks loose. There is no recovery possible from that situation. The entire command-based architecture between the I/O threads and the application threads is based on the assumption that the command channel is reliable - which is a perfectly reasonable assumption, given it's in-process communication.
The question is, why is Windows killing random loopback TCP connection? Can that be stopped, and if not, why?

> I'm also wondering why it uses local TCP connections internally?

It's TCP only on Windows. Posix systems have decent and usable inproc pipes (socket pairs IIRC), but at the time this was coded Windows did not. I do not know if that has changed as I am not familiar with Windows APIs. If there is an usable mechanism pull requests to add support for it would be very, very, very welcome since using TCP for this purpose has been a constant pain in the back on Windows.

**Comment by crosscode-nl** [comment]
I agree, loopback connections should be reliable, and not get killed, but it happens. We are currently investigating why it happens, but different sources on the internet mention the same issues. Most of the times some virtualization is involved. (VMWare or Hyper-V)

I think I would have used named pipes on Windows, but maybe you investigated that already and deemed them not suitable. The codebase of zeromq is not known to me yet. 

If I'm allowed by my customer then I will try to change the internal event pipe(s) to use named pipes, unless you already know that that is not going to work.

**Comment by bluca** [comment]
It has been proposed multiple times but a working implementation has never been done AFAIK. I wasn't around at that time so I can't reall add any insight.

From what I can read, the problem is that a new polling mechanism should be added together with the current epoll/kqueue/etc, IOCP, but it doesn't fit well with the model so it's not trivial to do.

See:

https://lists.zeromq.org/pipermail/zeromq-dev/2010-September/005941.html
https://github.com/zeromq/libzmq/issues/153
https://lists.zeromq.org/pipermail/zeromq-dev/2011-May/011092.html
http://somdoron.com/2014/11/netmq-iocp/

If someone were to implement a working version of this it would be great of course.

**Comment by crosscode-nl** [comment]
I've looked into it a bit and found that nanomsg does use IOCP, however, even that project uses a loopback TCP connection sometimes (but less than ZeroMQ). 

Also netmq uses loopback TCP connections, unfortunately. 

The biggest problem seems to be that both libraries are written around sockets, and Windows and Linux have different concepts of what can be sockets. So basically the need for a high performance and reliable messaging library for Windows exists. 

I'm thinking it might be easier to convince my customer to switch to Linux.

**Comment by bluca** [comment]
Windows always has to be special :-)

I guess the easiest fix would be to figure out what's killing TCP loopback connections (I mean that shouldn't really happen in a production system should it?) and fix it, or switch to Linux guests.

One day I do hope someone can contribute a working IOCP + socket pairs implementation. I'm not really a Windows dev so I'm afraid it's well out of my capabilities.

**Comment by sigiesec** [comment]
I would also be interested in improving performance and reliability under Windows, be it by using IOCP or by changing the internal sockets to named pipes). Unfortunately, I am not very familiar with IOCP. This might be something we could look at during the ZeroMQ Per-FOSDEM Hackathon, if there are some other Windows people besides me.

**Comment by bluca** [comment]
I've added it to the list - although it's quite complicated and unlikely to be doable in 2 days, at least a starting point could be done and be used later on to build on it

**Comment by rhkarls** [comment]
I had this problem (Win 10), but it was solved by uninstalling Nexus Access Client - if that is of any use to anyone else

**Comment by gdamore** [comment]
Legacy nanomsg had this problem too.  Martin's use of assertions to catch otherwise reasonable conditions is a mistake.  For nanomsg I've simply removed the assertion -- "unsignaling" either works, or it doesn't.  ECONNRESET (10054) is harmless in this case.

Now, its also the case that a) dynamic port allocation is far superior (I did this in NNG, and there are ways to ensure that it doesn't interfere with different processes with SO_EXLUSIVEADDRUSE) and b) the use of file descriptors for use in polling loops is really madness.

On item "b", a far far superior architecture involves the use of callbacks, or even condition variables.  Windows itself doesn't use these pollable file descriptors, except to satisfy POSIX equivalence.

In NNG (the nanomsg-next-generation rewrite I've created) we offer applications a superior callback based notification.  This is far more natural for many applications, and actually leads to greater scalability.  (I don't think ZeroMQ can adopt this kind of architecture easily -- I suspect the poll loop is kind of builtin to its heart).

(One other plus with callbacks -- significant performance benefit.  While synthetic benchmarks don't use polling, any real application does (absent a better mechanism like callbacks) and this means those real-world applications have to incur at least two extra system calls per send or per recv. )

PS: For the curious, nng is located at github.com/nanomsg/nng

**Comment by mmortal03** [comment]
I wonder if using NetWorx's WFP driver can also cause this, or if it's just NetWorx's TDI driver. I'm pretty sure I was using the WFP driver, and I was still experiencing this issue. 

You can check the file properties of networx.sys in C:\Windows\System32\drivers, and the details tab will tell you whether you are using the TDI or WFP driver.

**Comment by mxcoppell** [comment]
Any update to this issue? We are running ZMQ 4.2.3 and it had the same crash caused by "Assertion failed: Connection reset by peer".

Windows 10 64-bit Professional.

**Stack:** 
# ChildEBP RetAddr  
00 043ff7b8 5c42a8a0 KERNELBASE!RaiseException+0x62
01 043ff7e0 5c48c82d libzmq!zmq::zmq_abort+0x40 [c:\tradestation\platform\ts\private\ts10.0b2b\source\thirdparty\zeromq\4.2.3\src\err.cpp @ 83] 
02 043ff80c 5c42edca libzmq!zmq::signaler_t::recv_failable+0x16d [c:\tradestation\platform\ts\private\ts10.0b2b\source\thirdparty\zeromq\4.2.3\src\signaler.cpp @ 369] 
03 043ff82c 5c4678ab libzmq!zmq::mailbox_t::recv+0x14a [c:\tradestation\platform\ts\private\ts10.0b2b\source\thirdparty\zeromq\4.2.3\src\mailbox.cpp @ 88] 
04 043ff920 5c48076a libzmq!zmq::reaper_t::in_event+0x5b [c:\tradestation\platform\ts\private\ts10.0b2b\source\thirdparty\zeromq\4.2.3\src\reaper.cpp @ 89] 
05 043ff93c 5c47ffde libzmq!zmq::select_t::trigger_events+0x9a [c:\tradestation\platform\ts\private\ts10.0b2b\source\thirdparty\zeromq\4.2.3\src\select.cpp @ 121] 
06 0442f9f0 5c47ef69 libzmq!zmq::select_t::select_family_entry+0x16e [c:\tradestation\platform\ts\private\ts10.0b2b\source\thirdparty\zeromq\4.2.3\src\select.cpp @ 404] 
07 0442fb0c 5c480adb libzmq!zmq::select_t::loop+0x609 [c:\tradestation\platform\ts\private\ts10.0b2b\source\thirdparty\zeromq\4.2.3\src\select.cpp @ 372] 
08 0442fb14 5c4bd322 libzmq!zmq::select_t::worker_routine+0xb [c:\tradestation\platform\ts\private\ts10.0b2b\source\thirdparty\zeromq\4.2.3\src\select.cpp @ 416] 
09 0442fb28 5c3047d8 libzmq!thread_routine+0x22 [c:\tradestation\platform\ts\private\ts10.0b2b\source\thirdparty\zeromq\4.2.3\src\thread.cpp @ 46] 
0a 0442fb3c 5c304509 ucrtbased!invoke_thread_procedure+0x28 [minkernel\crts\ucrt\src\appcrt\startup\thread.cpp @ 92] 
0b 0442fb84 75308674 ucrtbased!thread_start<unsigned int (__stdcall*)(void *)>+0xa9 [minkernel\crts\ucrt\src\appcrt\startup\thread.cpp @ 115] 
0c 0442fb98 77d14b47 KERNEL32!BaseThreadInitThunk+0x24
0d 0442fbe0 77d14b17 ntdll!__RtlUserThreadStart+0x2f
0e 0442fbf0 00000000 ntdll!_RtlUserThreadStart+0x1b

**StdErr output:**
Assertion failed: Connection reset by peer (..\..\..\..\src\signaler.cpp:357)
Assertion failed: Connection reset by peer (..\..\..\..\src\signaler.cpp:357)
Assertion failed: Connection reset by peer (..\..\..\..\src\signaler.cpp:357)
Assertion failed: Connection reset by peer (..\..\..\..\src\signaler.cpp:357)

**Comment by mxcoppell** [comment]
Another question I have is why the stderr message didn't print the WSAGetLastErr() code in "[" and "]"?

```
#define wsa_assert(x)                                                          \
    do {                                                                       \
        if (unlikely (!(x))) {                                                 \
            const char *errstr = zmq::wsa_error ();                            \
            if (errstr != NULL) {                                              \
                fprintf (stderr, "Assertion failed: %s [%i] (%s:%d)\n",        \
                         errstr, WSAGetLastError (), _FILE, __LINE_);      \
                fflush (stderr);                                               \
                zmq::zmq_abort (errstr);                                       \
            }                                                                  \
        }                                                                      \
    } while (false)
```

**Comment by gdamore** [comment]
Well, it seems pretty clear that it isn't this assertion that is firing.

**Comment by gdamore** [comment]
I'm not sure what version of the code you're on, but this: https://github.com/zeromq/libzmq/blob/master/src/signaler.cpp#L356
suggests that you are not running on Windows but rather on Linux -- in which case that would be an eventfd which shouldn't have this errno, so I don't have a clear idea.  (Note, I'm not a maintainer for ZMQ and I don't regularly work with it).

The code in signaler.cpp seems fragile, and smells incredibly familiar to me from similar code in the nanomsg poller.   I abandoned most of that approach (except when *utterly* required by applications that insist that they only can receive events via a file descriptor) for NNG.  It's brittle, and *slow*, and unscalable.

(NNG makes use of event callbacks, using mutexes and condition variables, to provide a much more elegant form of notification back to the application.  See github.com/nanomsg/nng.)

**Comment by mxcoppell** [comment]
@gdamore That's my fault. I looked at the wsa_assert in https://github.com/zeromq/libzmq/blob/master/src/err.hpp.

**Comment by mxcoppell** [comment]
@gdamore Actually I looked again. The stderr message is printed out from wsa_assert(x) macro. 

https://github.com/zeromq/libzmq/blob/master/src/signaler.cpp#L373 is just calling the macro.
`        wsa_assert (last_error == WSAEWOULDBLOCK);
`

**Comment by mxcoppell** [comment]
Update: We did an comparison test with boost.asio with TCP connection on loopback interface. Got the same "Connection Reset by Peer" error. It doesn't look like it's ZMQ's problem. 

[Client Socket sudden lost while communicating with server and server is printing "Connection reset by peer" and "Connection reset"](https://social.technet.microsoft.com/Forums/ie/en-US/6a348332-32ff-4be2-9a0d-644a3bf971d5/client-socket-sudden-lost-while-communicating-with-server-and-server-is-printing-connection-reset?forum=winservergen)

**Comment by gdamore** [comment]
Something is resetting or closing TCP connections on the box.  Its not the first time I've heard of this, but it is incredibly toxic behavior.  In some circumstances it can be an overzealous admin, or firewall.  I'd try to figure out why connections are randomly being spuriously disconnected.

That said, I still contend that designs that rely on this TCP loopback for signaling are stupid.  With POSIX select and epoll driven loops you might not have a choice (but you usually have pipes or eventfds or socketpair to work around this problem), but on Windows using select() or WSApoll() to drive an event loop is stupid.

NNG doesn't do this.

I assume that ZeroMQ has a similar design to legacy nanomsg (mostly authored by the same person) and offers no other mechanism.

I doubt you can "fix" this other than by changing your design to use separate threads and blocking operations ... that's a big change, not very scalable, but it would completely eliminate the need for those loopback connections.

Or you can move away from ZMQ.  (Have I mentioned NNG...?? )

I probably won't comment further on this thread, since I'm not affiliated with the ZMQ project in any way.  (Peter tried to interest me in the project some months before his death, but I was too busy with nanomsg and really not interested in working on a C++/GPL based project.)

**Comment by gdamore** [comment]
(I know I said I probably wouldn't comment again... but... I can't resist.  Lol.)

You're partly right.

For TCP connections carrying user data, nanomsg, NNG, and ZMQ all will reconnect automatically.

The problem is that ZMQ and legacy nanomsg create a loopback connection using TCP *only on Windows* in order to provide support for getting a file descriptor that works with WSApoll() or select().   These programs use that connection to make the thread blocked in select or poll wake up (typically writing a byte, and then the library reads that byte after waking up in poll/select, etc.)

Under nanomsg, you know you're here if your program uses nn_getsockopt() to get the NN_RCVFD or NN_SNDFD.  With ZeroMQ, its the ZMQ_FD. 

The thing is, on Windows, this is an unnatural act.  Some programs do this this because they were designed for UNIX systems, and use poll() at the heart of an event loop.  But Windows has much better support for something called IO completion ports, and native asynchronous I/O mechanisms.  So programs and runtimes designed for Windows from the beginning have no need for this hackery.

Unfortunately, both ZMQ and legacy nanomsg were designed for POSIX first and Windows was mostly an after thought.  So they lack any kind of asynchronous support in their APIs, instead settling on nonblocking send and receive operations combined with that notification file descriptor.

NNG (the next generation of nanomsg) was designed to be asynchronous from the start, and uses callbacks (along with condition variables and mutex locks for synchronization) instead of poll-based solution.  It *offers* the same descriptor based approach, but whereas in nanomsg and ZMQ that's the *only* way to do asynchronous or non-blocking I/O, in NNG it's a second class citizen dropped in favor of more scalable, portable, performant, and *natural* operations.

If your program can use threads and synchronization primitives instead of a central event loop, you might not need the ZMQ_FD.  That would be more natural on Windows... while threads aren't super scalable on Windows, at least then you could use blocking socket operations and ditch the need for the TCP loopback connection altogether.  (Apart from any connection you might be using for your *data* -- but as I said, ZMQ, like all other similar systems, automatically reconnects *those* connections.)

**Comment by mxcoppell** [comment]
NNG sounds interesting! I will give it a try. Thanks @gdamore !

But, the reconnect logic you mentioned provided by messaging stacks - that part I am not clear about. If the connection is terminated by the peer, it won't be reconnected by ZMQ without application code logic (not from ZMQ). This is what we are discussing here, isn't it? Or you are talking about from TCP protocol point of view?

**Comment by bluca** [comment]
I've seen people complain about Windows randomly killing TCP connections just because, in some cases it was a third party network management tool of some sort (nexus-something maybe?), check for that.

Besides that, I think Microsoft added af_unix support in Windows 10 - that could be a good alternative to TCP loopback that won't suffer from this problem and should be relatively easy to implement, feel free to send a PR if you like

**Comment by gdamore** [comment]
I suspect that if there is Af_UNIX support that it won't work with WSApoll
and select. Historically those have been exclusive to winsock. That said
it's worth looking into.

**Comment by gdamore** [comment]
So I am pretty sure for zmq (and certainly for nanomsg family stacks) that
even on a peer disconnect the stack will attempt to reconnect.  This is in
the dialer side code and is done regardless of transport.  This is a big
piece of the self healing strategy these systems provide.

Of course it's up to the client to do this. The server side cannot initiate
a connection.

The thing is that this kind of logic is not provided for the event file
used with these file descriptors. Since both sides of the connection are in
the same process and managed by the library there was never any reason to
think that there would ever be a need. On UNIX systems using pipe() there
is no way for another process or an administrator to interfere here.
Windows is the loser here.

  G.

**Comment by mxcoppell** [comment]
@bluca 

When I said "It's a Window's thing", it's not accurate - it's actually something running on Windows 10 (anti-virus, packet filtering, monitoring) is interacting with Windows TCP/IP stack. 

The "Connection Reset by Peer" in my case only happen on specific computers. Interesting enough, when we do the traffic test on these target machines, the data speed on recv side is much slower than send. When we do the same test on the machines do not have loopback connection drop issue, data speeds of send & recv have much much smaller difference.

**Comment by bluca** [comment]
Yes there were similar reports in the past, unfortunately I can't remember the name of the software that was messing stuff up, nor find the issue I'm thinking about

**Comment by mmortal03** [comment]
@bluca , Networx is what you're talking about. It's discussed earlier in this thread.

**Comment by mxcoppell** [comment]
The problem is that what's been installed on the client machines - there is no way to predict. Better have a logic to recover in application code.

**Comment by liuqidev** [comment]
Same problem on Jupyter Notebook. I have reinstall anaconda and jupyter, but: 
```bash
Assertion failed: Connection reset by peer [10054] (bundled\zeromq\src\signaler.cpp:379)
Assertion failed: Connection reset by peer [10054] (bundled\zeromq\src\signaler.cpp:201)
Assertion failed: Connection reset by peer [10054] (bundled\zeromq\src\signaler.cpp:379)
Assertion failed: Connection reset by peer [10054] (bundled\zeromq\src\signaler.cpp:379)
Assertion failed: Connection reset by peer [10054] (bundled\zeromq\src\signaler.cpp:379)
Assertion failed: Connection reset by peer [10054] (bundled\zeromq\src\signaler.cpp:379)
[I 18:33:53.765 NotebookApp] KernelRestarter: restarting kernel (1/5), keep random ports
WARNING:root:kernel 597559d6-5ccb-42f9-b4b0-803047dc72f6 restarted
WARNING:root:kernel 597559d6-5ccb-42f9-b4b0-803047dc72f6 restarted
Assertion failed: Connection reset by peer [10054] (bundled\zeromq\src\signaler.cpp:379)

```

**Comment by liuqidev** [comment]
After:
> pip uninstall networkx

it still shows:

```
Assertion failed: Connection reset by peer (bundled\zeromq\src\signaler.cpp:298)
Assertion failed: Connection reset by peer (bundled\zeromq\src\signaler.cpp:298)
Assertion failed: Connection reset by peer (bundled\zeromq\src\signaler.cpp:298)
Assertion failed: Connection reset by peer (bundled\zeromq\src\signaler.cpp:298)
Assertion failed: Connection reset by peer (bundled\zeromq\src\signaler.cpp:298)
Assertion failed: Connection reset by peer (bundled\zeromq\src\signaler.cpp:298)
Assertion failed: Connection reset by peer (bundled\zeromq\src\signaler.cpp:181)
Assertion failed: Connection reset by peer (bundled\zeromq\src\signaler.cpp:298)
Assertion failed: Connection reset by peer (bundled\zeromq\src\signaler.cpp:298)
```

**Comment by karl-cenliming** [comment]
hi guys,
any update for this issue.

**Comment by roushanprasad** [comment]
I got this problem after I installed 'basemap' package to plot lat longs. Before that my Jupyter notebook was running perfectly fine. Anyone got any fix for this one ?

**Comment by GreatFireWall** [comment]
Hey guys,

I searched by Google: WFP zeromq, found this page. I think I should be able to provide some useful information.

I'm developing a network traffic redirection driver based on [WFP](https://docs.microsoft.com/en-us/windows/win32/fwp/windows-filtering-platform-start-page).

During the test, I ran various software to verify that my driver is running correctly. Which including [OpenShot Video Editor](https://www.openshot.org/). ([Its github page](https://github.com/OpenShot/openshot-qt))

**According to my driver design, local loopback traffic should not be redirected, they should be bypass by WFP filter.** All other softwares work as expected. 

**Only the OpenShot Video Editor not works as expected**: There is a loopback TCP connection that is captured by my driver when OpenShot starts.

So, I think look at the source code of OpenShot and see why it doesn't works as expected. Finally, I found [the code cause the loopback connection](https://github.com/OpenShot/openshot-qt/blob/b90e159c7052e872d144fb24850827baefd597c3/src/classes/logger_libopenshot.py#L70). It's using zeromq. So I searched by google then found this page...

Unfortunately, I don't understand the implementation of zeromq. At present, everyone seems to have no way of figuring out what caused it.

**Comment by bluca** [comment]
The implementation is quite simple in this regard: on Windows there's a TCP socket bound on INADDR_LOOPBACK and random port (0). If something on the system messes with that loopback connections, things go awry.

**Comment by bluca** [comment]
https://github.com/zeromq/libzmq/blob/master/src/ip.cpp#L423

**Comment by GreatFireWall** [comment]
> The implementation is quite simple in this regard: on Windows there's a TCP socket bound on INADDR_LOOPBACK and random port (0). If something on the system messes with that loopback connections, things go awry.

I had try to use [PacketSender](https://github.com/dannagle/PacketSender) for testing bypass loopback connection, it works as expected. It seems that WFP has a bug.

**Comment by maajdl** [comment]
> Something is resetting or closing TCP connections on the box. Its not the first time I've heard of this, but it is incredibly toxic behavior. In some circumstances it can be an overzealous admin, or firewall. I'd try to figure out why connections are randomly being spuriously disconnected.
> 
> That said, I still contend that designs that rely on this TCP loopback for signaling are stupid. With POSIX select and epoll driven loops you might not have a choice (but you usually have pipes or eventfds or socketpair to work around this problem), but on Windows using select() or WSApoll() to drive an event loop is stupid.
> 
> NNG doesn't do this.
> 
> I assume that ZeroMQ has a similar design to legacy nanomsg (mostly authored by the same person) and offers no other mechanism.
> 
> I doubt you can "fix" this other than by changing your design to use separate threads and blocking operations ... that's a big change, not very scalable, but it would completely eliminate the need for those loopback connections.
> 
> Or you can move away from ZMQ. (Have I mentioned NNG...?? )
> 
> I probably won't comment further on this thread, since I'm not affiliated with the ZMQ project in any way. (Peter tried to interest me in the project some months before his death, but I was too busy with nanomsg and really not interested in working on a C++/GPL based project.)

Hello Garrett,

I saw your posts here  regarding the error ‘Assertion failed: Connection reset by peer’ occurring in zmq.
I have asked at many places for a solution or work-around for this issue, but I could get no answer.
See for example [my post on jupyter.org](https://discourse.jupyter.org/t/assertion-failed-connection-reset-by-peer-what-could-i-do-about-it/2091) (I get this issues as a full time Jupyter user on Windows 8.1)

I was suggested that ‘some application’ would trigger this behavior, like the Firewall or a network monitoring application.
Could you give me suggestion about how I could identify a responsible application?
I don’t know how to monitor such things.

Thanks,

Michel

**Comment by zhangx258** [comment]
Same problem on Jupyter notebook,
any updates for this issue.

**Comment by sigiesec** [comment]
I recently implemented the `ipc` transport under Windows 10 using Unix domain sockets. It should be possible to also use Unix domain sockets on Windows 10 for the signaler socket. Since we don't know what causes the connection resets for the current TCP/IP signaler sockets, we cannot be sure if this solves the problem, but there is a chance. If someone else wants to work on this, have a look at the changes made by #3717. `zmq::fd_pair` must be adapted to use Unix domain sockets if available (which can be checked either at configuration time or at run-time). There is no `socketpair` on Windows 10 though, so the pair of sockets must be created manually.
