### ISSUE TITLE
Missing files in Tarball

### ISSUE THREAD

**Issue by hevy-CC4477** [zeromq/libzmq#1952]
Hi,

I tried to compile libzmq from the latest tarball (4.1.4) and it appears that some files/directory are missing : builds/cmake. Without these files we cannot compile the project with cmake.

Can you fix that ?

Also, why don't you tag your repository with release version?

Thanks,

**Comment by bluca** [comment]
It's fixed in libzmq master, I'll backport to 4.1.

**Comment by hevy-CC4477** [comment]
The tarball available here (http://download.zeromq.org/zeromq-4.1.4.zip, http://download.zeromq.org/zeromq-4.1.4.tar.gz) are still not fixed. When will it be ?

**Comment by bluca** [comment]
It will not, as it's already released, and we can't retroactively change the content of a release. It will be included in 4.1.5.

**Comment by dvj** [comment]
Note that 4.1.5 does not include version.rc.in, which is required for the cmake build on all platforms.

**Comment by bluca** [comment]
Is libzmq master make dist tarball also affected?

**Comment by bluca** [comment]
Self-answer: yes. I'll prepare a PR and send it to both. Thanks for bringing this up.

**Comment by bluca** [comment]
Opened #2096

**Comment by bluca** [comment]
@dvj - fixed in git for libzmq and zeromq4-1

**Comment by dvj** [comment]
great, thanks for the quick action on this!
