### ISSUE TITLE
Linker fails on master: undefined reference to `dladdr'

### ISSUE THREAD

**Issue by ishbir** [zeromq/libzmq#2033]
I ran `./autogen.sh && ./configure && make`. Problem is fixed by using `LIBS=-ldl ./configure && make`. I suspect something is up with autoconf and it doesn't add `dl` as a dependency.

O.S.: Arch Linux
GCC Version: 6.1.1

**Comment by bluca** [comment]
Version of autoconf, automake, libtool et al?

**Comment by ishbir** [comment]
autoconf (GNU Autoconf) 2.69
automake (GNU automake) 1.15
libtool (GNU libtool) 2.4.6
GNU ld (GNU Binutils) 2.26.0.20160501

**Comment by bluca** [comment]
I tried to reproduce on Debian sid, same version of the whole toolchain including the compiler, but can't.
Is it possible that something is up with your environment on Arch?

**Comment by bluca** [comment]
```
# ldd src/.libs/libzmq.so.5.0.0 
	linux-vdso.so.1 (0x00007fffd0e2c000)
	/usr/lib/cowdancer/libcowdancer.so (0x00007f658ff88000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f658fd7a000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f658fb5d000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f658f7dd000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f658f4de000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f658f13a000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f658ef24000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f658ed1f000)
	/lib64/ld-linux-x86-64.so.2 (0x000055c2f9413000)
```

libdl is linked without any workaround.

**Comment by ishbir** [comment]
I haven't changed the environment much. `printenv` gives me:
```
XDG_VTNR=1
SSH_AGENT_PID=774
XDG_SESSION_ID=c1
ANDROID_HOME=/opt/android-sdk
GLADE_PIXMAP_PATH=:
TERM=xterm
SHELL=/bin/bash
XDG_MENU_PREFIX=xfce-
ANDROID_SWT=/usr/share/java
WINDOWID=56775609
RUST_SRC_PATH=/home/user/rustc-nightly/src
USER=user
GLADE_MODULE_PATH=:
SSH_AUTH_SOCK=/tmp/ssh-hHmHOGLELY1z/agent.773
SESSION_MANAGER=local/generic:@/tmp/.ICE-unix/574,unix/generic:/tmp/.ICE-unix/574
MOZ_PLUGIN_PATH=/usr/lib/mozilla/plugins
XDG_CONFIG_DIRS=/etc/xdg
PATH=/home/user/.local/bin:/home/user/go/bin:/home/user/.local/bin:/home/user/go/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/opt/android-sdk/platform-tools:/opt/android-sdk/tools:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
MAIL=/var/spool/mail/user
DESKTOP_SESSION=xfce
QT_IM_MODULE=ibus
HG=/usr/bin/hg
PWD=/home/user/libzmq
XMODIFIERS=@im=ibus
LANG=en_US.UTF-8
HOME=/home/user
XDG_SEAT=seat0
SHLVL=4
CDM_SPAWN=519
LOGNAME=user
XDG_DATA_DIRS=/usr/local/share:/usr/share
DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus
GOPATH=/home/user/go
WINDOWPATH=1
XDG_RUNTIME_DIR=/run/user/1000
DISPLAY=:0.0
GLADE_CATALOG_PATH=:
XDG_CURRENT_DESKTOP=XFCE
GTK_IM_MODULE=ibus
COLORTERM=xfce4-terminal
XAUTHORITY=/home/user/.Xauthority
_=/usr/bin/printenv
```
Nothing out of the ordinary to my eyes. And I just tried a fresh build with `git clean -xdf && ./autogen.sh && ./configure && make` and got the same results. No idea where it's going wrong though.

**Comment by bluca** [comment]
This is so weird. Maybe autotools patches by the Arch maintainers affecting it?
Could you try to run `make V=1` to get the verbose output and upload it, together with config.status, to gist?

Also, does using CMake instead of autotools present the same issue?

**Comment by ishbir** [comment]
config.status: https://gist.github.com/ishbir/83ffebade64284770bee209afd63af15
`make V=1 |& tee make-output`: https://gist.github.com/ishbir/8255cc7867947b2ede8a6f92d26cdf31

And CMake works well with the defaults.

**Comment by ambitslix** [comment]
Confirmed the same happens on Fedora 23.

**Comment by bluca** [comment]
Honestly have no idea why with the same toolchain I can't reproduce on debian unstable, I can't see anything obviously wrong in the logs.

**Comment by bluca** [comment]
The only workaround I can suggest is to build without the perf binaries: `./configure --disable-perf`
Of course any suggestion, help and PR to fix this properly is more than welcome!
There's no difference in the Makefile.am from how we deal with the perf binaries and the test binaries, so I'm really baffled as for why the former don't work, sorry.

**Comment by ehildum** [comment]
Ran into this building on CentOS 6.8 with libsodium 1.0.7.  In configure.ac, there are checks for libpthread and librt, but no check for libdl:

...
# Checks for libraries
AC_CHECK_LIB([pthread], [pthread_create])
AC_CHECK_LIB([rt], [clock_gettime])
...

I suggest adding
AC_CHECK_LIB([dl], [dladdr])

then automake, autoconf

I tried to do this, but CentOS 6.8 versions of autotools aren't recent enough.  Maybe somebody with later autotools could do this and post an updated configure script.

**Comment by bluca** [comment]
That's a good point, it is missing. I'll give it a shot, thanks for the suggestion.

**Comment by bluca** [comment]
dladdr is needed only when building with libunwind for backtrace support, so that's why it's not seen in all cases. Also Debian 7 build is complaining about overlinking to libdl, but Debian 8 and 9 complain about libgcc_s, so I guess the symbol moved or is provided by that in more recent versions of the compiler toolchain?

**Comment by ehildum** [comment]
The only reference I found to libdl in the code is in err.cpp, zmq::print_backtrace().  As you say, it is conditional on building with libunwind. Sounds like a hassle to handle in the general platform build setup.

**Comment by ViewSky** [comment]
I put the code on some machine support(bdw，or hsw) do 'make', and copy them back to the target machine. Final, on the target machine 
` make install`
The reason is 

Glibc adds two functions not described by POSIX, with prototypes

`#define _GNU_SOURCE         /* See feature_test_macros(7) */`
`#include <dlfcn.h>`
`int dladdr(void *addr, Dl_info *info);`
`void *dlvsym(void *handle, char *symbol, char *version);`
Here's the link: https://linux.die.net/man/3/dladdr

**Comment by bluca** [comment]
Does it work for you now with the latest version from the repository? It should be fixed

**Comment by alex179ohm** [comment]
if the latest version is 4.2.0. gentoo still broken: https://bugs.gentoo.org/show_bug.cgi?id=602244

**Comment by bluca** [comment]
Sorry, I mean latest version from this git repository, could you try building from here please?

**Comment by Whissi** [comment]
Our Gentoo ebuild *does* contain the patch from issue  #2206 aka commit 1b3fcbd3eead8f1f59f3e9472319d58ce6b52bb7, see https://gitweb.gentoo.org/repo/gentoo.git/tree/net-libs/zeromq/zeromq-4.2.0.ebuild#n28

@alex179ohm: Could you please confirm that the ebuild you tried is current and does contain the patch (t was added later after the first report came in).

**Comment by alex179ohm** [comment]
build without patch works fine with a fresh clone of the master branch.
