### ISSUE TITLE
Global static mutex random_sync causes order of destruction bug

### ISSUE THREAD

**Issue by aaronovz1** [zeromq/libzmq#2915]
# Issue description

When using zmqpp with libzmq 4.2.3 there is an order of destruction bug in static builds if there are contexts defined globally/static. This is due to the global static mutex random_sync in random.cpp being destructed before the context is destructed.

I think the better approach would be to have client application control the initialization of sodium_init() via the zmq::random_open()/close() function. Client code would need to call this at start/end of main(). I think adding a couple functions like zmq_init() and zmq_destroy() to wrap these kind of init calls would do the trick.

# Environment

* libzmq version (commit hash if unreleased): 4.2.3
* OS: Ubuntu 16.04

# What's the actual result? (include assertion message & call stack if applicable)

```
Program received signal SIGABRT, Aborted.
0x00007ffff5534428 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
54	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) list
49	in ../sysdeps/unix/sysv/linux/raise.c
(gdb) bt
#0  0x00007ffff5534428 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
#1  0x00007ffff553602a in __GI_abort () at abort.c:89
#2  0x00000000012f39ee in zmq::zmq_abort (errmsg_=errmsg_@entry=0x7ffff568c10a "Invalid argument") at src/err.cpp:87
#3  0x00000000012fde65 in zmq::mutex_t::lock (this=0x4431200 <random_sync>) at src/mutex.hpp:122
#4  zmq::scoped_lock_t::scoped_lock_t (mutex_=..., this=<synthetic pointer>) at src/mutex.hpp:168
#5  zmq::random_close () at src/random.cpp:110
#6  0x00000000012ee546 in zmq::ctx_t::~ctx_t (this=0x61600000f980, __in_chrg=<optimized out>) at src/ctx.cpp:124
#7  0x00000000012eeb65 in zmq::ctx_t::terminate (this=0x61600000f980) at src/ctx.cpp:201
#8  0x00000000012dc711 in zmqpp::context::terminate() ()
#9  0x0000000000485eef in zmqpp::context::~context (this=0x4431188 <zmqpp::actor::actor_pipe_ctx_>, __in_chrg=<optimized out>) at ../../../../trunk/thirdparty/zmqpp4.2.0/include/zmqpp/context.hpp:100
#10 0x00007ffff5538ff8 in __run_exit_handlers (status=0, listp=0x7ffff58c35f8 <__exit_funcs>, run_list_atexit=run_list_atexit@entry=true) at exit.c:82
#11 0x00007ffff5539045 in __GI_exit (status=<optimized out>) at exit.c:104
#12 0x00007ffff551f837 in __libc_start_main (main=0x4792c0 <main(int, char**)>, argc=2, argv=0x7fffffffdb58, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fffffffdb48) at ../csu/libc-start.c:325
#13 0x00000000004463a9 in _start ()
```

# What's the expected result?

Correct order of destruction and no abort being thrown.

**Comment by bluca** [comment]
> I think the better approach would be to have client application control the initialization of sodium_init() via the zmq::random_open()/close() function. Client code would need to call this at start/end of main(). I think adding a couple functions like zmq_init() and zmq_destroy() to wrap these kind of init calls would do the trick.

Sorry, but we cannot do this - it would be an API breakage.

Given the problem is in zmqpp, is there any way to solve it there? Can we fix the ordering?

**Comment by aaronovz1** [comment]
The problem is actually in libzmq because if any client code uses it, and defines a context globally will run into this behaviour, because the order of destruction is undefined and that mutex will always have a possibility of being destroyed before the context.
The zmqpp library can only get around it by somehow removing the need to have a context defined globally. I have reported this issue on their repo and will see if a workaround can be found for the time being.

By the way, this wasn't an issue in libzmq 4.2.2.

________________________________

**Comment by bluca** [comment]
Yes it's new and necessary as a bugfix for: https://github.com/zeromq/libzmq/issues/2632
The issue is that bug is much more likely to happen than libzmq static + zmqpp static + global variables, which is a much rarer common case.

Can you avoid using a global variable for the context as a workaround?

**Comment by sigiesec** [comment]
Urgh, having non-trivial global statics in a static library is a road to disaster. I did not notice this was introduced.

I think this particular problem could be solved by using an atomic counter for random_refcount (at least on platforms where atomic increment/decrement is available, and does not require use of a mutex again).

**Comment by bluca** [comment]
The problem with the atomic counter is that it's non-blocking - so there might race conditions where the first thread sets the counter and starts to initialise the library, while a second thread arriving at the same time sees that the counter is non-zero so it jumps over the initialisation and then goes on to use crypto before the other thread has finished initialising it :-/

**Comment by sigiesec** [comment]
True... What about a pair of atomic counter and atomic pointer like this in pseudo-code:
```
if (atomic_counter.increment () == 0) { 
  Obj *obj = new (Obj);
  initialize(obj);
  atomic_pointer.store( obj );
} else {
  while (!atomic_pointer.load() ) { yield(); }
}
```

**Comment by bluca** [comment]
That could work, but it's basically a reimplementation of a mutex.. is there something specific about the mutex class that is causing issues?

**Comment by sigiesec** [comment]
The problem with mutex_t is that it has a non-trivial destructor.

**Comment by bluca** [comment]
POSIX mutex can be initialised statically with PTHREAD_MUTEX_INITIALIZER, which _should_ mean there is no need to destroy it. It could be a solution for *nix. And for Windows we could use the fake-mutex that @sigiesec mentioned.

```
When an automatically or dynamically allocated mutex is no longer required, it should be destroyed using pthread_mutex_destroy(). (It is not necessary to call pthread_mutex_destroy() on a mutex that was statically initialized using PTHREAD_MUTEX_INITIALIZER.)
```

https://books.google.co.uk/books?id=2SAQAQAAQBAJ&pg=PA640&lpg=PA640#v=onepage&q&f=false

**Comment by aaronovz1** [comment]
ZMQ wraps mutex with mutex_t, what way do you recommend that would allow this one problematic static mutex to be initialized using PTHREAD_MUTEX_INITIALIZER? Extend the class with something like static_mutex_t? Or an argument passed into constructor?

**Comment by bluca** [comment]
as far as I understand it can't use the class because then it won't be initialised statically and it also will have a destructor which is what is causing the issue in the first place - so the only solution is some ugly hack and just use pthread APIs inline in that file

**Comment by bluca** [comment]
@sigiesec I tried an implementation on Windows - tests seems to pass, could you please have a quick look and let me know if it would work? It uses a static CriticalSection and it initialises it with InitOnceExecuteOnce:

https://github.com/bluca/libzmq/commit/d0602f08952c35e3e42506d9685f8e21c9c52057

**Comment by bluca** [comment]
@sigiesec ping

**Comment by sigiesec** [comment]
So this does not introduce a global library shutdown function, right?
I don't think this is a viable solution :( Since DeleteCriticalSection is never called, leak detectors will complain, and I don't think this is a good idea.
I think the only way to implement this without a global library shutdown function is to implement a spin-lock with atomics.

**Comment by bluca** [comment]
So it leaks even if it's on the stack? Bummer. Why can't Windows do POSIX...

**Comment by bluca** [comment]
I'll send a PR with the POSIX fix then, given the problem was reported on Linux. Then a Windows solution can be added later if needed.

**Comment by sigiesec** [comment]
What do you mean by "on the stack"? It is a global variable... It is not really specified if there are other resources associated with it (kernel objects), this might depend on the Windows version.

Besides that, a pthread implementation might also cause a leak if pthread_mutex_destroy is not called.

**Comment by sigiesec** [comment]
After thinking a bit more about this, also the POSIX solution does not solve the problem, since the initialization order is also undefined within a link unit. Either the global variables must be made static locals (with proper thread-safe initialization equivalent to std::call_once), or explicit global library initialization/shutdown functions must be provided.

**Comment by bluca** [comment]
I mean, it's not malloc'ed, so memory associated with it will (should?) not leak - but you are right and there might be other resources, I really don't know how it works, just implemented based on the MSDN API description.

For POSIX, from what I can read it's safe to skip the _destroy when using the static initialiser, as that was the purpose, on BSD (and so on OSX) and Linux.

**Comment by sigiesec** [comment]
No, that can't be. Global variables are initialized in an undefined order of compilation units within a link unit. This has nothing to do with what PTHREAD_MUTEX_INITIALIZER actually does.

If you have a.cpp containing 
```
int x = 42;
```

and b.cpp containing
```
extern int x;
int y = x;
```

the order in which x and y are initialized is undefined (and so the value of y is undefined). It may differ even for different linker runs.

**Comment by bluca** [comment]
Sure but this is just a single file - the mutex is not referenced from anywhere else, so why is it a problem?

**Comment by sigiesec** [comment]
Ok, I see my example didn't hit the point.

Suppose a.cpp contains
```
int x = 42;
int get_x() { return x; }
```
and b.cpp contains
```
int get_x();
int y = get_x();
```
The problem is still the same. x may or may not be initialized when get_x is called during initialization of y.

Or, somewhat closer to our stuff with a.cpp:
```
bool initialized = true;
int foo() { zmq_assert(initialized); return 42; }
```
and b.cpp
```
int foo();
int y = foo();
```

This might initialize y to 42, but it might also trigger the assertion, depending on the random initialization order (and the uninitialized value "initialized" happens to have).

**Comment by bluca** [comment]
But in those examples (and in the links you pasted) there are 2 globals, with a dependency. The problem is that there is no ordering enforcement in that dependency. I understand that.

But in this case there is only one global variable - the mutex. Which is called at some point after zmq_ctx_new() is called at some pointer after main() - and main() will always be called after all globals are initialised, right?

**Comment by sigiesec** [comment]
No, in the issue there is such a global variable depending on another. However, while the equivalent of a.cpp is in libzmq, the equivalent of b.cpp is not part of libzmq, but of the application.

**Comment by sigiesec** [comment]
With C++11, this can portably be solved by local thread-safe statics, initialized using std::call_once. local statics have always been initialized on first use, but before C++11, this was not required to be done in a thread-safe manner (gcc supports this for quite some time AFAIK, but MSVC did not support this until VS2012 or so).

So I don't think this can be solved at all portably for pre-C++11 platforms without extra initialization/shutdown functions, which the application is required to call at the correct times.

But maybe it can be left like it was for such platforms, and use std::call_once on platforms that support it?

**Comment by bluca** [comment]
> No, in the issue there is such a global variable depending on another. However, while the equivalent of a.cpp is in libzmq, the equivalent of b.cpp is not part of libzmq, but of the application.

Sorry but I still don't get it - the context is just a pointer. It will get initialised after main(). How can it race with the global mutex?

**Comment by sigiesec** [comment]
Consider b.cpp:
```
zmqpp::context application_global_context;
```
zmq_ctx_new is called in the ctor of zmqpp::context.

**Comment by sigiesec** [comment]
Please have a look at https://github.com/ZMQers/libzmq/compare/837bdf161ca7...8cdfc8b9dd9a

**Comment by bluca** [comment]
Ah right - so the problem is introduced by the wrapper also introducing a class into the mix. Got it.

**Comment by bluca** [comment]
The diff looks fine, thanks
